name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:    
    - name: Env Setup
      uses: actions/checkout@v4

    - name: Run Cypress 
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_MAILSLURP_API_KEY: ${{secrets.CYPRESS_MAILSLURP_API_KEY}}

    - name: Run Browserstack
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{secrets.BROWSERSTACK_USERNAME}}
        access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
    - run: npx browserstack-cypress run --config --nv 18.17.0 
    