name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:    
    - name: 'Env Setup and Run Cypress'
      uses: actions/checkout@v4
    - uses: actions/setup-node@v2
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: Run Cypress
      uses: cypress-io/github-action@v6
    - run: npx browserstack-cypress run --config --nv 18.17.0 
    