name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:    
    - name: 'Env Setup and Run Cypress'
      uses: 'browserstack/github-actions/setup-env@master'
    - uses: actions/checkout@v4
    - uses: cypress-io/github-action@v6
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        CYPRESS_MAILSLURP_API_KEY: ${{secrets.CYPRESS_MAILSLURP_API_KEY}}
    - run: npx browserstack-cypress run --config --nv 18.17.0 
    